title: Thomas Grover
#logo: relative/path/to/image/of/me
description: Welcome to my portfolio! I am a statistics student at North Carolina State University where I also study psychology and data science.
show_downloads: False
theme: jekyll-theme-slate
